# Đề bài về nhà

## Yêu cầu

- Tự viết code cho mô hình Linear Regression theo công thức đã được dạy trong buổi lý thuyết trên lớp.
- Tự viết hàm dự đoán.
- Huấn luyện cả mô hình của thư viện và mô hình mình tự viết.
- In ra các trọng số: w0, w1, w2, ..., wn của cả 2 mô hình đã huấn luyện để quan sát và so sánh.
- Dự đoán dữ liệu tập test bằng cả 2 mô hình (mô hình thư viện thì dùng hàm predict() của thư viện, mô hình tự viết dùng hàm dự đoán tự viết), in ra kết quả bằng Dataframe như trong bài thực hành trên lớp.
- Tính RMSE trên tập test cho cả 2 mô hình và so sánh.

## Dữ liệu

Tập dữ liệu giá nhà ở Boston đã có sẵn trên sklearn, dữ liệu đã được chuẩn hóa và chia thành tập train, tập test

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import math 

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Đọc dữ liệu 

Dữ liệu về giá nhà ở Boston được hỗ trợ bởi sklearn, đọc dữ liệu thông qua hàm `datasets.load_boston()` 

Xem thêm các bộ dữ liệu khác tại https://scikit-learn.org/stable/datasets/index.html#toy-datasets. 

Dữ liệu được chia thành các thành phần data và target như tập diabetes. Dữ liệu cũng đã được chuẩn hóa, chỉ cần gọi ra và huấn luyện

In [2]:
# lay du lieu dataset - du lieu ve giá nhà
from sklearn.datasets import fetch_openml
dataset = fetch_openml(name='boston', version=1, parser='auto')

print("Số chiều dữ liệu input: ", dataset.data.shape)
print("Số chiều dữ liệu target: ", dataset.target.shape)
print()

print("5 mẫu dữ liệu đầu tiên:")
print("input: ", dataset.data[:5])
print("target: ",dataset.target[:5])

Số chiều dữ liệu input:  (506, 13)
Số chiều dữ liệu target:  (506,)

5 mẫu dữ liệu đầu tiên:
input:        CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0     15.3
1  0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0     17.8
2  0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0     17.8
3  0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0     18.7
4  0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0     18.7

        B  LSTAT
0  396.90   4.98
1  396.90   9.14
2  392.83   4.03
3  394.63   2.94
4  396.90   5.33
target:  0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

**Chia dữ liệu làm 2 phần training 362 mẫu và testing 80 mẫu**

In [3]:
# cat nho du lieu, lay 1 phan cho qua trinh thu nghiem,
# chia train test cac mau du lieu
# dataset_X = dataset.data[:, np.newaxis, 2]
dataset_X = dataset.data

dataset_X_train = dataset_X[:404]
dataset_y_train = dataset.target[:404]

dataset_X_test = dataset_X[405:]
dataset_y_test = dataset.target[405:]

# Xây dựng mô hình

## Xây dựng mô hình bằng thư viện

In [4]:
regr = linear_model.LinearRegression()

## Xây dựng mô hình Linear Regression tự viết

In [5]:
def linear_regression(X_train,y_train):
    one = np.ones((X_train.shape[0],1))
    Xbar = np.concatenate((one,X_train),axis=1)
    A=np.dot(Xbar.T, Xbar)
    b = np.dot(Xbar.T,y_train)
    w_lr = np.dot(np.linalg.pinv(A),b)
    coef = w_lr[1:]
    intercept = w_lr[0]
    return coef, intercept

## Hàm test mô hình tự viết

In [6]:
def predict(intercept, coef, X_test):
    # Chỉ cần 1 dòng duy nhất là xong
    return np.dot(X_test, coef) + intercept

# Huấn luyện mô hình

## Huấn luyện mô hình của thư viện

In [7]:
regr.fit(dataset_X_train, dataset_y_train)
print("[w1, ... w_n] = ", regr.coef_)
print("w0 = ", regr.intercept_)

[w1, ... w_n] =  [-2.02135297e-01  4.41276341e-02  5.26739364e-02  1.88474315e+00
 -1.49281487e+01  4.76038673e+00  2.88734527e-03 -1.30025278e+00
  4.61661953e-01 -1.55434673e-02 -8.11632369e-01 -1.97174433e-03
 -5.32273431e-01]
w0 =  30.077166922902244

## Training mô hình bằng Linear regression tự viết

In [8]:
X_train_matrix = np.array(dataset_X_train, dtype=float)
y_train_matrix = np.array(dataset_y_train, dtype=float)
coef, intercept = linear_regression(X_train_matrix, y_train_matrix)

print("[w1, ... w_n] = ", coef)
print("w0 = ", intercept)

[w1, ... w_n] =  [-2.02135297e-01  4.41276341e-02  5.26739364e-02  1.88474315e+00
 -1.49281487e+01  4.76038673e+00  2.88734527e-03 -1.30025278e+00
  4.61661953e-01 -1.55434673e-02 -8.11632369e-01 -1.97174433e-03
 -5.32273431e-01]
w0 =  30.077166919125375

# Dự đoán các mẫu dữ liệu

## Dự đoán các mẫu dữ liệu theo mô hình của thư viện

In [9]:
X_test_matrix = np.array(dataset_X_test, dtype=float)
y_test_matrix = np.array(dataset_y_test, dtype=float)
dataset_y_pred_lib = regr.predict(X_test_matrix)
pd.DataFrame(data=np.array([dataset_y_test, dataset_y_pred_lib,
                            abs(dataset_y_test - dataset_y_pred_lib)]).T,
             columns=["Thực tế", "Dự đoán", "Lệch"])

c:\Users\bpscm\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

     Thực tế    Dự đoán       Lệch
0        5.0   3.787057   1.212943
1       11.9   6.640550   5.259450
2       27.9  21.312765   6.587235
3       17.2  15.412714   1.787286
4       27.5  23.652298   3.847702
..       ...        ...        ...
96      22.4  23.755044   1.355044
97      20.6  22.081673   1.481673
98      23.9  28.181773   4.281773
99      22.0  26.572420   4.572420
100     11.9  22.020566  10.120566

[101 rows x 3 columns]

## Dự đoán các mẫu dữ liệu tính theo linear regression tự viết

In [10]:
X_test_matrix = np.array(dataset_X_test, dtype=float)
y_test_matrix = np.array(dataset_y_test, dtype=float).flatten() 

# Dự đoán bằng hàm mới
dataset_y_pred = predict(intercept, coef, X_test_matrix).flatten()

# Vẽ bảng (Lưu ý: Dùng y_test_matrix thay cho dataset_y_test)
bang_so_sanh = pd.DataFrame(
    data=np.array([y_test_matrix, dataset_y_pred, abs(y_test_matrix - dataset_y_pred)]).T,
    columns=["Thực tế", "Dự đoán", "Lệch"]
)

bang_so_sanh

     Thực tế    Dự đoán       Lệch
0        5.0   3.787057   1.212943
1       11.9   6.640550   5.259450
2       27.9  21.312765   6.587235
3       17.2  15.412714   1.787286
4       27.5  23.652298   3.847702
..       ...        ...        ...
96      22.4  23.755044   1.355044
97      20.6  22.081673   1.481673
98      23.9  28.181773   4.281773
99      22.0  26.572420   4.572420
100     11.9  22.020566  10.120566

[101 rows x 3 columns]

## Đánh giá mô hình linear regression của thư viện

In [13]:
loss = math.sqrt(mean_squared_error(dataset_y_test, dataset_y_pred_lib))
print("lỗi :",loss)

lỗi : 5.749521870254022

## Đánh giá mô hình linear regression tự viết

In [14]:
loss = math.sqrt(mean_squared_error(dataset_y_test, dataset_y_pred))
print("lỗi :",loss)

lỗi : 5.74952187016078